# Generated by Django 3.2 on 2021-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0002_mgmlist0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='zhongyuanMgm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(default='', max_length=50)),
                ('new', models.CharField(default='', max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
