# Generated by Django 3.1.7 on 2021-03-19 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0002_prize_rate_winner_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize_rate',
            name='today',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
