# Generated by Django 3.1.7 on 2021-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0003_prize_rate_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdemo_Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
