# Generated by Django 3.2 on 2021-04-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0011_alter_snake_player_highscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spinwheel_Done',
            new_name='scratchDemo_Done',
        ),
    ]
