# Generated by Django 3.2 on 2021-08-05 20:24

from django.db import migrations, models
import turntableApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0018_pei_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='puduImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(default='uploads\\product-1.jpg', upload_to=turntableApp.models.get_image_path)),
            ],
        ),
    ]
