# Generated by Django 3.2 on 2021-08-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0019_puduimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='puduimg',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
