# Generated by Django 3.2 on 2021-08-06 09:06

from django.db import migrations, models
import turntableApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0021_auto_20210806_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='zhongyuanMgm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(default='', max_length=50)),
                ('new', models.CharField(default='', max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='puduimg',
            name='img',
            field=models.ImageField(default='uploads\\product-1.jpg', upload_to=turntableApp.models.get_image_path),
        ),
    ]
