# Generated by Django 3.2 on 2021-08-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0022_zhongyuanmgm'),
        ('turntableApp', '0023_ci_done'),
    ]

    operations = [
    ]
