# Generated by Django 3.1.7 on 2021-08-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0023_ci_done'),
        ('turntableApp', '0022_zhongyuanmgm'),
    ]

    operations = [
    ]
