# Generated by Django 3.1.7 on 2021-08-06 12:28

from django.db import migrations, models
import turntableApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('turntableApp', '0024_merge_20210806_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puduimg',
            name='img',
            field=models.ImageField(default='uploads/product-1.jpg', upload_to=turntableApp.models.get_image_path),
        ),
    ]
